/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getAddressEncoder, getBytesDecoder, getBytesEncoder, getProgramDerivedAddress, getStructDecoder, getStructEncoder, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlyUint8Array, type TransactionSigner, type WritableAccount, type WritableSignerAccount } from '@solana/kit';
import { ONLEASH_PROGRAM_ADDRESS } from '../programs';
import { expectAddress, getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLOSE_BUDGET_DISCRIMINATOR = new Uint8Array([205, 29, 212, 191, 194, 200, 168, 24]);

export function getCloseBudgetDiscriminatorBytes() { return fixEncoderSize(getBytesEncoder(), 8).encode(CLOSE_BUDGET_DISCRIMINATOR); }

export type CloseBudgetInstruction<TProgram extends string = typeof ONLEASH_PROGRAM_ADDRESS, TAccountOwner extends string | AccountMeta<string> = string, TAccountAgentBudget extends string | AccountMeta<string> = string, TAccountMint extends string | AccountMeta<string> = string, TAccountBudgetAta extends string | AccountMeta<string> = string, TAccountOwnerAta extends string | AccountMeta<string> = string, TAccountTokenProgram extends string | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountOwner extends string ? WritableSignerAccount<TAccountOwner> & AccountSignerMeta<TAccountOwner> : TAccountOwner, TAccountAgentBudget extends string ? WritableAccount<TAccountAgentBudget> : TAccountAgentBudget, TAccountMint extends string ? ReadonlyAccount<TAccountMint> : TAccountMint, TAccountBudgetAta extends string ? WritableAccount<TAccountBudgetAta> : TAccountBudgetAta, TAccountOwnerAta extends string ? WritableAccount<TAccountOwnerAta> : TAccountOwnerAta, TAccountTokenProgram extends string ? ReadonlyAccount<TAccountTokenProgram> : TAccountTokenProgram, ...TRemainingAccounts]>;

export type CloseBudgetInstructionData = { discriminator: ReadonlyUint8Array;  };

export type CloseBudgetInstructionDataArgs = {  };

export function getCloseBudgetInstructionDataEncoder(): FixedSizeEncoder<CloseBudgetInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]), (value) => ({ ...value, discriminator: CLOSE_BUDGET_DISCRIMINATOR }));
}

export function getCloseBudgetInstructionDataDecoder(): FixedSizeDecoder<CloseBudgetInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)]]);
}

export function getCloseBudgetInstructionDataCodec(): FixedSizeCodec<CloseBudgetInstructionDataArgs, CloseBudgetInstructionData> {
    return combineCodec(getCloseBudgetInstructionDataEncoder(), getCloseBudgetInstructionDataDecoder());
}

export type CloseBudgetAsyncInput<TAccountOwner extends string = string, TAccountAgentBudget extends string = string, TAccountMint extends string = string, TAccountBudgetAta extends string = string, TAccountOwnerAta extends string = string, TAccountTokenProgram extends string = string> =  {
  owner: TransactionSigner<TAccountOwner>;
agentBudget: Address<TAccountAgentBudget>;
mint: Address<TAccountMint>;
budgetAta?: Address<TAccountBudgetAta>;
ownerAta?: Address<TAccountOwnerAta>;
tokenProgram?: Address<TAccountTokenProgram>;
}

export async function getCloseBudgetInstructionAsync<TAccountOwner extends string, TAccountAgentBudget extends string, TAccountMint extends string, TAccountBudgetAta extends string, TAccountOwnerAta extends string, TAccountTokenProgram extends string, TProgramAddress extends Address = typeof ONLEASH_PROGRAM_ADDRESS>(input: CloseBudgetAsyncInput<TAccountOwner, TAccountAgentBudget, TAccountMint, TAccountBudgetAta, TAccountOwnerAta, TAccountTokenProgram>, config?: { programAddress?: TProgramAddress } ): Promise<CloseBudgetInstruction<TProgramAddress, TAccountOwner, TAccountAgentBudget, TAccountMint, TAccountBudgetAta, TAccountOwnerAta, TAccountTokenProgram>> {
  // Program address.
const programAddress = config?.programAddress ?? ONLEASH_PROGRAM_ADDRESS;

 // Original accounts.
const originalAccounts = { owner: { value: input.owner ?? null, isWritable: true }, agentBudget: { value: input.agentBudget ?? null, isWritable: true }, mint: { value: input.mint ?? null, isWritable: false }, budgetAta: { value: input.budgetAta ?? null, isWritable: true }, ownerAta: { value: input.ownerAta ?? null, isWritable: true }, tokenProgram: { value: input.tokenProgram ?? null, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>;


// Resolve default values.
if (!accounts.budgetAta.value) {
accounts.budgetAta.value = await getProgramDerivedAddress({ programAddress: 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>, seeds: [getAddressEncoder().encode(expectAddress(accounts.agentBudget.value)), getBytesEncoder().encode(new Uint8Array([6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169])), getAddressEncoder().encode(expectAddress(accounts.mint.value))] });
}
if (!accounts.ownerAta.value) {
accounts.ownerAta.value = await getProgramDerivedAddress({ programAddress: 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>, seeds: [getAddressEncoder().encode(expectAddress(accounts.owner.value)), getBytesEncoder().encode(new Uint8Array([6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169])), getAddressEncoder().encode(expectAddress(accounts.mint.value))] });
}
if (!accounts.tokenProgram.value) {
accounts.tokenProgram.value = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
}

const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
return Object.freeze({ accounts: [getAccountMeta(accounts.owner), getAccountMeta(accounts.agentBudget), getAccountMeta(accounts.mint), getAccountMeta(accounts.budgetAta), getAccountMeta(accounts.ownerAta), getAccountMeta(accounts.tokenProgram)], data: getCloseBudgetInstructionDataEncoder().encode({}), programAddress } as CloseBudgetInstruction<TProgramAddress, TAccountOwner, TAccountAgentBudget, TAccountMint, TAccountBudgetAta, TAccountOwnerAta, TAccountTokenProgram>);
}

export type CloseBudgetInput<TAccountOwner extends string = string, TAccountAgentBudget extends string = string, TAccountMint extends string = string, TAccountBudgetAta extends string = string, TAccountOwnerAta extends string = string, TAccountTokenProgram extends string = string> =  {
  owner: TransactionSigner<TAccountOwner>;
agentBudget: Address<TAccountAgentBudget>;
mint: Address<TAccountMint>;
budgetAta: Address<TAccountBudgetAta>;
ownerAta: Address<TAccountOwnerAta>;
tokenProgram?: Address<TAccountTokenProgram>;
}

export function getCloseBudgetInstruction<TAccountOwner extends string, TAccountAgentBudget extends string, TAccountMint extends string, TAccountBudgetAta extends string, TAccountOwnerAta extends string, TAccountTokenProgram extends string, TProgramAddress extends Address = typeof ONLEASH_PROGRAM_ADDRESS>(input: CloseBudgetInput<TAccountOwner, TAccountAgentBudget, TAccountMint, TAccountBudgetAta, TAccountOwnerAta, TAccountTokenProgram>, config?: { programAddress?: TProgramAddress } ): CloseBudgetInstruction<TProgramAddress, TAccountOwner, TAccountAgentBudget, TAccountMint, TAccountBudgetAta, TAccountOwnerAta, TAccountTokenProgram> {
  // Program address.
const programAddress = config?.programAddress ?? ONLEASH_PROGRAM_ADDRESS;

 // Original accounts.
const originalAccounts = { owner: { value: input.owner ?? null, isWritable: true }, agentBudget: { value: input.agentBudget ?? null, isWritable: true }, mint: { value: input.mint ?? null, isWritable: false }, budgetAta: { value: input.budgetAta ?? null, isWritable: true }, ownerAta: { value: input.ownerAta ?? null, isWritable: true }, tokenProgram: { value: input.tokenProgram ?? null, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>;


// Resolve default values.
if (!accounts.tokenProgram.value) {
accounts.tokenProgram.value = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
}

const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
return Object.freeze({ accounts: [getAccountMeta(accounts.owner), getAccountMeta(accounts.agentBudget), getAccountMeta(accounts.mint), getAccountMeta(accounts.budgetAta), getAccountMeta(accounts.ownerAta), getAccountMeta(accounts.tokenProgram)], data: getCloseBudgetInstructionDataEncoder().encode({}), programAddress } as CloseBudgetInstruction<TProgramAddress, TAccountOwner, TAccountAgentBudget, TAccountMint, TAccountBudgetAta, TAccountOwnerAta, TAccountTokenProgram>);
}

export type ParsedCloseBudgetInstruction<TProgram extends string = typeof ONLEASH_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
owner: TAccountMetas[0];
agentBudget: TAccountMetas[1];
mint: TAccountMetas[2];
budgetAta: TAccountMetas[3];
ownerAta: TAccountMetas[4];
tokenProgram: TAccountMetas[5];
};
data: CloseBudgetInstructionData; };

export function parseCloseBudgetInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedCloseBudgetInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
  // TODO: Coded error.
  throw new Error('Not enough accounts');
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { owner: getNextAccount(), agentBudget: getNextAccount(), mint: getNextAccount(), budgetAta: getNextAccount(), ownerAta: getNextAccount(), tokenProgram: getNextAccount() }, data: getCloseBudgetInstructionDataDecoder().decode(instruction.data) };
}