/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { assertAccountExists, assertAccountsExist, combineCodec, decodeAccount, fetchEncodedAccount, fetchEncodedAccounts, fixDecoderSize, fixEncoderSize, getAddressDecoder, getAddressEncoder, getBooleanDecoder, getBooleanEncoder, getBytesDecoder, getBytesEncoder, getI64Decoder, getI64Encoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, getU8Decoder, getU8Encoder, transformEncoder, type Account, type Address, type EncodedAccount, type FetchAccountConfig, type FetchAccountsConfig, type FixedSizeCodec, type FixedSizeDecoder, type FixedSizeEncoder, type MaybeAccount, type MaybeEncodedAccount, type ReadonlyUint8Array } from '@solana/kit';

export const AGENT_BUDGET_DISCRIMINATOR = new Uint8Array([235, 116, 220, 20, 119, 72, 229, 139]);

export function getAgentBudgetDiscriminatorBytes() { return fixEncoderSize(getBytesEncoder(), 8).encode(AGENT_BUDGET_DISCRIMINATOR); }

export type AgentBudget = { discriminator: ReadonlyUint8Array; owner: Address; delegate: Address; mint: Address; totalAllowance: bigint; spentTotal: bigint; perTxLimit: bigint; dailyLimit: bigint; dailySpent: bigint; dailyResetAt: bigint; expiresAt: bigint; paused: boolean; nonce: bigint; bump: number;  };

export type AgentBudgetArgs = { owner: Address; delegate: Address; mint: Address; totalAllowance: number | bigint; spentTotal: number | bigint; perTxLimit: number | bigint; dailyLimit: number | bigint; dailySpent: number | bigint; dailyResetAt: number | bigint; expiresAt: number | bigint; paused: boolean; nonce: number | bigint; bump: number;  };

/** Gets the encoder for {@link AgentBudgetArgs} account data. */
export function getAgentBudgetEncoder(): FixedSizeEncoder<AgentBudgetArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['owner', getAddressEncoder()], ['delegate', getAddressEncoder()], ['mint', getAddressEncoder()], ['totalAllowance', getU64Encoder()], ['spentTotal', getU64Encoder()], ['perTxLimit', getU64Encoder()], ['dailyLimit', getU64Encoder()], ['dailySpent', getU64Encoder()], ['dailyResetAt', getI64Encoder()], ['expiresAt', getI64Encoder()], ['paused', getBooleanEncoder()], ['nonce', getU64Encoder()], ['bump', getU8Encoder()]]), (value) => ({ ...value, discriminator: AGENT_BUDGET_DISCRIMINATOR }));
}

/** Gets the decoder for {@link AgentBudget} account data. */
export function getAgentBudgetDecoder(): FixedSizeDecoder<AgentBudget> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['owner', getAddressDecoder()], ['delegate', getAddressDecoder()], ['mint', getAddressDecoder()], ['totalAllowance', getU64Decoder()], ['spentTotal', getU64Decoder()], ['perTxLimit', getU64Decoder()], ['dailyLimit', getU64Decoder()], ['dailySpent', getU64Decoder()], ['dailyResetAt', getI64Decoder()], ['expiresAt', getI64Decoder()], ['paused', getBooleanDecoder()], ['nonce', getU64Decoder()], ['bump', getU8Decoder()]]);
}

/** Gets the codec for {@link AgentBudget} account data. */
export function getAgentBudgetCodec(): FixedSizeCodec<AgentBudgetArgs, AgentBudget> {
    return combineCodec(getAgentBudgetEncoder(), getAgentBudgetDecoder());
}

export function decodeAgentBudget<TAddress extends string = string>(encodedAccount: EncodedAccount<TAddress>): Account<AgentBudget, TAddress>;
export function decodeAgentBudget<TAddress extends string = string>(encodedAccount: MaybeEncodedAccount<TAddress>): MaybeAccount<AgentBudget, TAddress>;
export function decodeAgentBudget<TAddress extends string = string>(encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>): Account<AgentBudget, TAddress> | MaybeAccount<AgentBudget, TAddress> {
  return decodeAccount(encodedAccount as MaybeEncodedAccount<TAddress>, getAgentBudgetDecoder());
}

export async function fetchAgentBudget<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<AgentBudget, TAddress>> {
  const maybeAccount = await fetchMaybeAgentBudget(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeAgentBudget<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<AgentBudget, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeAgentBudget(maybeAccount);
}

export async function fetchAllAgentBudget(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<AgentBudget>[]> {
  const maybeAccounts = await fetchAllMaybeAgentBudget(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeAgentBudget(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<AgentBudget>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeAgentBudget(maybeAccount));
}

export function getAgentBudgetSize(): number {
  return 170;
}